package tstexc

// Code generated by tstexcgen DO NOT EDIT.

type Func1Dep4In1Out[D1, I1, I2, I3, I4, O1 any] struct {
	execute func(D1) func(I1, I2, I3, I4) O1
	D1      D1
	i1      I1
	i2      I2
	i3      I3
	i4      I4
}

func NewFunc1Dep4In1Out[D1, I1, I2, I3, I4, O1 any](f func(D1) func(I1, I2, I3, I4) O1) Func1Dep4In1Out[D1, I1, I2, I3, I4, O1] {
	return Func1Dep4In1Out[D1, I1, I2, I3, I4, O1]{execute: f}
}

func (f Func1Dep4In1Out[D1, I1, I2, I3, I4, O1]) Execute(options ...func(Func1Dep4In1Out[D1, I1, I2, I3, I4, O1]) Func1Dep4In1Out[D1, I1, I2, I3, I4, O1]) O1 {
	g := f
	for _, option := range options {
		g = option(g)
	}
	return g.execute(g.D1)(g.i1, g.i2, g.i3, g.i4)
}

func (f Func1Dep4In1Out[D1, I1, I2, I3, I4, O1]) DefaultDep1(x D1) Func1Dep4In1Out[D1, I1, I2, I3, I4, O1] {
	g := f
	g.D1 = x
	return g
}

func (f Func1Dep4In1Out[D1, I1, I2, I3, I4, O1]) DefaultIn1(x I1) Func1Dep4In1Out[D1, I1, I2, I3, I4, O1] {
	g := f
	g.i1 = x
	return g
}

func (f Func1Dep4In1Out[D1, I1, I2, I3, I4, O1]) DefaultIn2(x I2) Func1Dep4In1Out[D1, I1, I2, I3, I4, O1] {
	g := f
	g.i2 = x
	return g
}

func (f Func1Dep4In1Out[D1, I1, I2, I3, I4, O1]) DefaultIn3(x I3) Func1Dep4In1Out[D1, I1, I2, I3, I4, O1] {
	g := f
	g.i3 = x
	return g
}

func (f Func1Dep4In1Out[D1, I1, I2, I3, I4, O1]) DefaultIn4(x I4) Func1Dep4In1Out[D1, I1, I2, I3, I4, O1] {
	g := f
	g.i4 = x
	return g
}

func (Func1Dep4In1Out[D1, I1, I2, I3, I4, O1]) WithDep1(x D1) func(Func1Dep4In1Out[D1, I1, I2, I3, I4, O1]) Func1Dep4In1Out[D1, I1, I2, I3, I4, O1] {
	return func(f Func1Dep4In1Out[D1, I1, I2, I3, I4, O1]) Func1Dep4In1Out[D1, I1, I2, I3, I4, O1] {
		return f.DefaultDep1(x)
	}
}

func (Func1Dep4In1Out[D1, I1, I2, I3, I4, O1]) WithIn1(x I1) func(Func1Dep4In1Out[D1, I1, I2, I3, I4, O1]) Func1Dep4In1Out[D1, I1, I2, I3, I4, O1] {
	return func(f Func1Dep4In1Out[D1, I1, I2, I3, I4, O1]) Func1Dep4In1Out[D1, I1, I2, I3, I4, O1] {
		return f.DefaultIn1(x)
	}
}

func (Func1Dep4In1Out[D1, I1, I2, I3, I4, O1]) WithIn2(x I2) func(Func1Dep4In1Out[D1, I1, I2, I3, I4, O1]) Func1Dep4In1Out[D1, I1, I2, I3, I4, O1] {
	return func(f Func1Dep4In1Out[D1, I1, I2, I3, I4, O1]) Func1Dep4In1Out[D1, I1, I2, I3, I4, O1] {
		return f.DefaultIn2(x)
	}
}

func (Func1Dep4In1Out[D1, I1, I2, I3, I4, O1]) WithIn3(x I3) func(Func1Dep4In1Out[D1, I1, I2, I3, I4, O1]) Func1Dep4In1Out[D1, I1, I2, I3, I4, O1] {
	return func(f Func1Dep4In1Out[D1, I1, I2, I3, I4, O1]) Func1Dep4In1Out[D1, I1, I2, I3, I4, O1] {
		return f.DefaultIn3(x)
	}
}

func (Func1Dep4In1Out[D1, I1, I2, I3, I4, O1]) WithIn4(x I4) func(Func1Dep4In1Out[D1, I1, I2, I3, I4, O1]) Func1Dep4In1Out[D1, I1, I2, I3, I4, O1] {
	return func(f Func1Dep4In1Out[D1, I1, I2, I3, I4, O1]) Func1Dep4In1Out[D1, I1, I2, I3, I4, O1] {
		return f.DefaultIn4(x)
	}
}
